# Production Docker Compose Configuration
# Optimized for production deployment

version: '3.8'

services:
  # Redis - Message broker and cache
  redis:
    image: docker.xuanyuan.me/library/redis:7-alpine
    container_name: intrascribe-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - intrascribe-network

  # STT Microservice
  stt-service:
    image: intrascribe/stt-service:latest
    container_name: intrascribe-stt-prod
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - STT_MODEL_DIR=iic/SenseVoiceSmall
      - STT_OUTPUT_DIR=/tmp/audio
      - LOG_LEVEL=INFO
    volumes:
      - stt_models:/app/models
      - temp_audio:/tmp/audio
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 120s  # Allow time for model loading
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - intrascribe-network

  # Speaker Diarization Microservice
  diarization-service:
    image: intrascribe/diarization-service:latest
    container_name: intrascribe-diarization-prod
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - PYANNOTE_MODEL=pyannote/speaker-diarization-3.1
      - MIN_SEGMENT_DURATION=1.0
      - LOG_LEVEL=INFO
    volumes:
      - speaker_models:/app/models
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 120s  # Allow time for model loading
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - intrascribe-network

  # Main API Service
  api-service:
    image: intrascribe/api-service:latest
    container_name: intrascribe-api-prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STT_SERVICE_URL=http://stt-service:8001
      - SPEAKER_SERVICE_URL=http://diarization-service:8002
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LIVEKIT_API_URL=${LIVEKIT_API_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy
      stt-service:
        condition: service_healthy
      diarization-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      - intrascribe-network

  # Agent Service (production scaling)
  agent-service:
    image: intrascribe/agent-service:latest
    container_name: intrascribe-agent-prod
    restart: unless-stopped
    environment:
      - LIVEKIT_API_URL=${LIVEKIT_API_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STT_SERVICE_URL=http://stt-service:8001
      - API_SERVICE_URL=http://api-service:8000
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy
      stt-service:
        condition: service_healthy
      diarization-service:
        condition: service_healthy
      api-service:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 2G
      replicas: 2  # Scale for production
    networks:
      - intrascribe-network

# Volumes for persistent data
volumes:
  redis_data:
    driver: local
  stt_models:
    driver: local
  speaker_models:
    driver: local
  temp_audio:
    driver: local

# Network for service communication
networks:
  intrascribe-network:
    driver: bridge
